scripts/acronym.js
scripts/parking.js

Implement multiple acronyms in !!acro and UQ parking with !parking

---

scripts/urban.js

fix for multi line definitions

---

bin/hubot
external-scripts.json
package.json

Youtube search and DevOps reactions gif poster.

Added a few scripts

---

external-scripts.json
scripts/reaction.js

So the idea is that users can register and use images/gifs with the bot and then anyone can use the registered gifs/images.
It just means leggy could have a !mrw duck command that was a rubber duck.
Think 'bigger, free emotes'
atm the system could be abused and used to link to any resource or just repeat text. I'm going to look into enforcing links only and maybe somehow checking them to ensure validity.
tl;dr register text with bot and have the bot spit it back out as needed.

I would like to add a reaction gif/image bot script thing

---

scripts/acronym.js
scripts/parking.js
scripts/reaction.js
scripts/urban.js
scripts/weather.js
scripts/welcome.js

The code indention in the javascript files is currently inconsistent, with 2-space and tabs both used. I've changed the javascript file to use tabs only.
The [rationale](http://www.movementarian.org/docs/whytabs/) is that this will maintain consistency while allowing each developer to use the indention width they are most comfortable with. For example, it seems that some people like 2-space-wide indents, which I find very hard to read. Rather than making a hard decision that will annoy some people, tabs give each developer the freedom to choose what they prefer, while maintaining easy interoperability. 
At the very least, the consolidation of all indents into one format should allow for a global change to a given indentation style.

Change inconsistant indentation

---

package.json
scripts/computers.js
scripts/conversation.js

Added !computers command
Added conversation support, it's acting funny but it'll work for now

!computers and hubot-conversation

---

scripts/computers.js
scripts/conversation.js

- geocodes search term (using Google Maps API) and returns closest BOM radar via kd.tree
- changed the emoji and spacing of computers.js

closest BOM radar and computers.js adjustments

---

scripts/caesar.js

!caesar<n> <text>
Applies a Caesar shift of n to text, if n is not specified it will default to 47 (half of the mod)

Added caesar.js

---

package.json
scripts/events.js

!events - Outputs upcoming UQCS events

Added events.js

---

bin/hubot
bin/hubot.cmd
scripts/acronym.js
scripts/caesar.js
scripts/computers.js
scripts/events.js
scripts/parking.js
scripts/reaction.js
scripts/uqfinal.js
scripts/urban.js
scripts/weather.js

With this (and the `--alias "!"` patch) commands can be called via:
`uqcsbot <command>`
`uqcsbot !<command>`
`!command`
`!!command`

Standardized commands

---

scripts/computers.js
scripts/events.js
scripts/weather.js

Fixes the documentation error and stops the event spam

Remove UTF BOM and update events

---

scripts/events.js
scripts/wakie.js

- Untested to due restrictions

Initial commit of wakie.js

---

scripts/wakie.js

The excess commits were due to me forgetting to update the fork before pushing (thus needing to fix it and I'm shit at git)

Fixed my mistake of left-over bracket

---

scripts/events.js

Hide the end time month and day if it is the same as the start time for the event.

Improve event time formatting

---

package.json
scripts/uqfinal.js
scripts/welcome.js
scripts/werewolf-ai.js

- Evaluation
- Credit message
- Automatic percentage upgrade ie 0.5 -> 50%

UQFinal improvements + Werewolf AI

---

external-scripts.json

Which I made. It allows you to add options during the vote

Use a better voting package

---

scripts/wikipedia.js

i suppose this might be useful

let the bot search wikipedia

---

scripts/log.js

I'm hoping there isn't anything that lets people check the brain by commands (as this logs all channels).

Added basic chat history support

---

scripts/log.js

- Also replaced "append" with "push"

Moved brain load as the load listener didn't work

---

scripts/log.js

- Also added number of logged messages to status

Fixed mistake with getting current room

---

scripts/log.js

Doesn't really need to be merged, it just fixed #76

Logging: Messages on disabled status

---

scripts/events.js
scripts/wakie.js
scripts/welcome.js

Added 'all' to !events

---

scripts/voteythumbs.js

Fixed the add_reaction function

---

scripts/voteythumbs.js

- Voteythumbs previously required the number of up votes - down votes
to be greater than half the channel. Now it just requires >50% up or
>50% down

Fixed voteythumbs count & new message

---

scripts/cat.js

Added moss cat command to uqcsbot.
No surprise, it prints the moss cat.

Added moss cat

---

scripts/shell.js

- Enables more advanced use of uqcsbot, currently only substitutes in
values from other commands

Added !shell

---

scripts/ecp.js

Added ecp.js, to find the URLs of electronic course profiles.

Course Profiles!

---

scripts/xkcd.js

Added command !xkcd which will take a query string and output the
most relavent xkcd comic with respects to that query string.

Added !xkcd command

---

scripts/xkcd.js

When searching for a number in !xkcd it will now get the xkcd with the matching id, or yell at you if it does not find a match.

Added id search to !xkcd

---

scripts/staticice.js

Added a staticice script to find best electronics prices in aus

Add staticice script

---

scripts/parking.js

Parking: Conifer Knoll is staff-only now.

---

scripts/whatsdue.js

Prints a list of assessment due given a list of course codes.
Initial commit! functionality may change :) just wanted to dip my toes into hubot scripts.

Added !whatsdue command

---

scripts/whatsdue.js

Compiled assessment printouts to just a single message to prevent out-of-order printing. Added some simple formatting.

Updated !whatsdue

---

scripts/ecp.js

Added a check for robot.adapter.client for people testing. Cleaned some stuff up.

(ecp command) Hopefully fixed querying in a course room.

---

scripts/whatsdue.js

Added a check for robot.adapter.client for people testing. Cleaned some stuff up.

(whatsdue command) Hopefully fixed querying in a course room.

---

scripts/dominos.js

Added a coupon finder for dominos, using the same coupon search engine that ozbargin uses (https://www.couponese.com/store/dominos.com.au/).

Coupon finder for dominos

---

scripts/wakie.js

Untested but will ping 2 people again. If it pings the same person twice then they should buy a lotto ticket

Unfixed 5pm question time

---

README.md

Added better instructions to get the bot running on a dummy slack.
Also added a note to encourage people to ask in slack if they encounter any issues.

Improved instructions on running locally

---

scripts/reactify.js

Fixed issue where it could roll the same react multiple times
Fixed issue where it fails if any non-alphanumeric/space chars are used

Fixed some issues in reactify

---

scripts/ping.js

Bot has to have admin permissions. `!ping (everyone|here|channel)` Will only work for users in the allowed list, or in channels with users less than 50 users. I added all the committee to the allowed list. Not tested very well.

Added !ping

---

scripts/uqfinal.js

Changed uqfinal to use api. #124

---

package.json
scripts/welcome.js

As per title :)
Fixes:
- Milestones (#150)
- Display names (#161)

Refactored !welcome and fixed(?) member milestones

---

scripts/wavie.js

Waves at people as they enter or leave rooms :)

Added !wavie script

---

scripts/wakie.js

When wakie wakie is run, have uqcsbot hit 'em up with the ol :loading:

Add :loading: react to wakie wakie

---

scripts/wavie.js

Okay no dependencies this time ._.
Added wavie.js, which waves at people as they join/leave rooms :)
Now checks whether room is public/private based off room id prefix letter, and will only :wave: if the last message if that message was a person joining/leaving (aka it won't wave at another message that comes after the person joining/leaving but before the API request is responded to)

Added wavie.js (again)

---

scripts/wavie.js

Added #announcements exception which fixes #182 
Also fixed incorrect groups API calls/checks

Fixes to wavie.js

---

scripts/latex.js

Latex script was being called at the wrong times. Fixed prob
Solves: #181

Fix latex script

---

scripts/voteythumbs.js

Fix voteythumbs typo

---

scripts/computers.js

Add emoji for Whitty computers

---

scripts/wakie.js

Turns out :loading: isn't even an emoji, what a lol
-Added a list of waiting emojis that will be selected from at random to react with

Added list of waiting emojis for wakie.js

---

README.md
bin/hubot

I've setup a test slack with 4 bot tokens for people to use. If someone else could test they can follow my instructions and get a bot connected that'd be appreciated :)

Add test slack info to readme 

---

scripts/ping.js

!ping was not working. I fixed it but requires an admin to generate a legacy api token from here: https://api.slack.com/custom-integrations/legacy-tokens
This token should be set as an env variable under: `SLACK_ADMIN_TOKEN`
It's a bit of a hacky implementation but I can't see any other way to do it.

Fixed !ping

---

bin/hubot

Slack disabled some tokens because they scan repos. This should _probably_ fix that :)

Avoid spying from the slack overlords.

---

scripts/urban.js

Have tested to confirm still works and updated instructions to post-Mitch style.

After fighting with git to do the thing, we have an !urban

---

scripts/urban.js

fixed link unfurling, this time (hopefully) without including all pending PRs 👍

fixed link unfurling

---

bin/hubot
scripts/purescript.js

- Minimised purescript error printout to just error message (no stack trace) and added reassuring message to new devs
- Added default database url as a fallback if none is provided

Make building less troublesome and scary for new devs

---

scripts/wavie.js

Cleaned up wavie.js and converted it to using data store over API calls

---

scripts/welcome.js

Cleaned up welcome.js and converted it to using data store over API calls

---

scripts/wakie.js

Cleaned up wakie.js and converted it to using data store over API calls

---

scripts/cookbook.js
scripts/dog.js
scripts/uqfinal.js
scripts/urban.js

Made !uqfinal dynamic by semester, added !dog (like !cat) and !cookbook (link)

---

scripts/stats.js

- Fixed some funky italics
- Fixed an incorrect `command` variable name
- Stored rooms using their name instead of id to allow for searching
- Adds another decimal of precision to percentages

Fixes to !stats

---

uqcsbot/api.py
uqcsbot/base.py

Better documentation than most of my code, but still untested as I have very limited internet access.
Simplifies API calls a bit, and makes the API look cool :joy:

API wrapper - Allow calling API through standard dotted methods

---

setup.py
uqcsbot/__init__.py
uqcsbot/api.py
uqcsbot/base.py

Again this is untested code. Hopefully works fine. It at least removes a few deps.

First pass at using RTM client

---

setup.py
uqcsbot/api.py
uqcsbot/base.py
uqcsbot/scripts/wakie.py

Doesn't actually do wakie implementation while tom writes channel wrapper.
It even has async support.

Added cronjob event handling support

---

scripts/whatsdue.js

changed url

---

scripts/js.js

Fixed bug with incorrect code escaping on exception.
ES6.
Made code readable

Improvements to !js

---

scripts/wavie.js

Fixes the "double wave" situation

Prevent wavie.js executing for #general (which has its own wave)

---

scripts/urban.js

fixed urban rach condition and formatting

---

uqcsbot/__init__.py

Thought it might be helpful to know what bot you were assigned to.
Since I wanted to use the logger for this message I went ahead and did my best at changing all the errors on the bot assignment to use the logger. Not at all familiar with this so if I've done something wrong please do yell at me.

Bot name printing on dev start.

---

uqcsbot/api.py

As per title, adds rate limit handling to api calls.
Comments and feedback appreciated :^)
Fixes #249.

Added rate limiting to api calls

---

uqcsbot/api.py
uqcsbot/scripts/test.py

Cursor was never being updated because we were updating the wrong kwarg. Also patched an unchecked get for `members`.

Fixed pagination kwarg bug

---

uqcsbot/base.py
uqcsbot/scripts/acronym.py
uqcsbot/scripts/ecp.py
uqcsbot/scripts/events.py
uqcsbot/scripts/help.py
uqcsbot/scripts/mock.py
uqcsbot/scripts/pastexams.py
uqcsbot/scripts/voteythumbs.py
uqcsbot/scripts/wakie.py
uqcsbot/scripts/welcome.py
uqcsbot/scripts/wiki.py
uqcsbot/scripts/wolfram.py

Most async scripts were using `bot.post_message` synchronously, which would block the thread running tasks.
This PR introduces `bot.as_async`, which is a fixed version of `AsyncBotWrapper` that runs all functions using the event loop's threadpool executor, and provides an async `api` property.

Utilise asyncio more

---

uqcsbot/scripts/define.py
uqcsbot/scripts/wolfram.py

Adds a command that returns the dictionary definition of the argument.

Added define command

---

uqcsbot/scripts/pastexams.py

Tom left a dangling async :angery: <3
Cleaned it up a little while I was there

Fixed past exams

---

uqcsbot/scripts/hoogle.py

*With newlines for `--verbose`*
*Without newlines for `--verbose`*

Add !hoogle

---

test/conftest.py
uqcsbot/api.py
uqcsbot/scripts/voteythumbs.py

This PR does a few lil things:
* Added logging of API call errors
* Fixed misnamed repr variable
* Cleaned up some PEP 8 issues
* Removed unused `update_members`
* Patched lingering bad merge issues (`Command.from_message`)

Fixed a few things

---

uqcsbot/__init__.py
uqcsbot/base.py

Was broken, unused and deemed not necessary to fix and/or keep.

Removed 'local' mode

---

test/conftest.py
uqcsbot/api.py
uqcsbot/scripts/welcome.py

also fixed a few bugs in @trm's untested code <3

Added mocking for users.list API call

---

test/conftest.py
test/helpers.py
test/test_cat.py
test/test_dog.py
test/test_echo.py
test/test_id.py
test/test_mock.py
test/test_no_handler.py
test/test_test_setup.py
test/test_welcome.py
test/test_yt.py
tox.ini
uqcsbot/__init__.py
uqcsbot/__main__.py
uqcsbot/api.py
uqcsbot/base.py
uqcsbot/scripts/attic.py
uqcsbot/scripts/define.py
uqcsbot/scripts/events.py
uqcsbot/scripts/pastexams.py
uqcsbot/scripts/radar.py
uqcsbot/scripts/urban.py
uqcsbot/scripts/welcome.py
uqcsbot/scripts/wolfram.py
uqcsbot/util/uq_course_util.py

Fixed all lint issues. Added coverage report output. Added test linting.

---

test/test_welcome.py
uqcsbot/api.py
uqcsbot/scripts/wakie.py
uqcsbot/scripts/welcome.py

Tested in dev, but we might still get bugged out wakie. Sorry this didn't land in time for wakie today.

Theoretically fix wakie + welcome

---

test/conftest.py
test/test_voteythumbs.py
uqcsbot/scripts/voteythumbs.py
uqcsbot/scripts/yt.py

As per title :^) lets us test reaction-based scripts. Added `!voteythumbs` tests to show this (and cleaned up + simplified it while I was there).

Added mocking for reactions.add and reactions.remove API calls

---

test/test_umart.py
uqcsbot/scripts/umart.py

Fixed some intended usage of umart. :+1: 
Added some moar tests.
Please ignore the commit message where I forget that !! causes the last command to be substituted in.

moar umart

---

uqcsbot/util/uq_course_util.py

as per title.
also standardised `course_name` as a course variable name

Added course logging for DateSyntaxException

---

uqcsbot/scripts/conduct.py

Added !conduct

---

test/test_mock.py
uqcsbot/scripts/mock.py

Added ability to mock text

---

uqcsbot/scripts/holiday.py

Posts a message on general with a holiday from https://www.timeanddate.com/holidays/fun/ at 9am.
Unfortunately, I couldn't think of a better name for the script. 
Fixes #275.

Add a "What weird day is it" announcement 

---

test/test_mock.py
uqcsbot/scripts/mock.py

Auto-merging since this was already "reviewed" in #366

Readded !mock for text

---

uqcsbot/scripts/jobs.py

fixed welcome channel bug ("-" instead of "_") and changed to consistent " use over '.

fixed welcome channel bug

---

README.md

Fix link to Slack in readme.

---

uqcsbot/scripts/welcome.py

Updated welcome message with new committee and code of conduct

---

uqcsbot/scripts/dominos.py
uqcsbot/utils/uq_course_utils.py

Added !dominos

---

uqcsbot/scripts/urban.py

fixed multiword urban

---

uqcsbot/scripts/xkcd.py

As requested in issue #394, some context to the latest XKCD comics being posted. 
First PR **ever**, apologies if I have broken protocol

#394 context for XKCD comic

---

uqcsbot/scripts/xkcd.py

#394 xkcd English corrections

---

uqcsbot/utils/command_utils.py

Adding more react emoji to `LOADING_REACTS`, `SUCCESS_REACTS` and `HYPE_REACTS`.

Adding more reacts

---

uqcsbot/scripts/events.py

Put event name before venue.
From:
To:

changed event message format

---

uqcsbot/scripts/events.py

Reverts UQComputingSociety/uqcsbot#406

Revert "changed event message format"

---

test/test_http.py
uqcsbot/scripts/http.py

Added !http command

---

uqcsbot/scripts/jobs.py

now reminder messages about job postings will come in a single message. Join messages will still come in individual messages.

single message reminders

---

uqcsbot/scripts/weather.py

`uqcsbot` will now give a loading emoji reaction to `!weather` while it retrieves the BOM data.

Added @loading_status to !weather

---

test/test_crisis.py
uqcsbot/scripts/crisis.py

Both do the same thing - provide a list of crisis resources for quick reference.
Happy to add any other resources that may be of use :)

Create !crisis, !emergency and !mentalhealth

---

uqcsbot/api.py
uqcsbot/scripts/jobs.py
uqcsbot/utils/message_utils.py

added message utils and fixed jobs bug

---

test/test_parking.py
uqcsbot/scripts/parking.py

Love your work @bradleysigma, couldn't help but tweak it though ;)

!parking typo fix "availible"

---

test/test_uqfinal.py
uqcsbot/scripts/uqfinal.py

Now gives average scores needed when more than one assessment missing.
Accepts "%" in scores.  
Gives requirements for all passing grades.  
Reiterates inputs for both decimals and percentages.  
Names final assessment.  
Lists assessment if no marks given.

`!uqfinal` improvements

---

uqcsbot/scripts/whatsdue.py
uqcsbot/utils/uq_course_utils.py

Adds a link to the assessment page that whatsdue scrapes from

---

uqcsbot/scripts/history.py

This will, once a day, find a pin that was posted on the same date in a previous year*, and repost it in the same channel.

Adding daily "on this day" using channel pins

---

test/test_events.py
uqcsbot/scripts/events.py

Add source filter to `!events`

---

uqcsbot/scripts/welcome.py

Changing `welcome.py` to list the 2020 committee members.

New committee members.

---

uqcsbot/scripts/welcome.py

Reworded most existing sections. More info and links about:
- Downloading mobile/desktop apps.
- Updating profile
- Links to repo

Welcome Revamp

---

test/test_welcome.py

Two of the !events tests remain failing.
Appears failures are only local?

fixed welcome test

---

setup.py
test/test_events.py
uqcsbot/scripts/events.py
uqcsbot/scripts/jobs.py

Will need to work out later if we want to check message formatting, and if so how to capture attachment output text.

Updated Calendar Format to Distinguish UQCS from ITEE

---

test/test_emoji_log.py
uqcsbot/scripts/emoji_log.py

I am incapable of reading console output correctly

Fix emoji log style

---

test/test_events.py
uqcsbot/scripts/events.py

Adds a second calendar for external events and [tags] for external and ITEE events:

Add External Events

---

uqcsbot/scripts/yelling.py

CHEERING MUST BE LOUD

---

test/test_binify.py
uqcsbot/scripts/binify.py

Converts a binary string to an ascii string or vice versa

Create `!binify` command

---

uqcsbot/scripts/weather.py

Bot will automatically disapprove of itself when it cannot reach the BOM server.

Autodisapproval (weather.py)

---

test/test_bgg.py
uqcsbot/scripts/bgg.py

Creates the `!bgg` command, which uses the Board Game Geek API to fetch data about the required board game.

Create `!bgg` command

---

uqcsbot/scripts/bgg.py

Also, message length now limited to 1'500 characters, not 4'000.

Max and Min players are now sorted as integers, not strings

---

uqcsbot/scripts/jobs.py

Weekly reminder that [link.uqcs.org/jobs](link.uqcs.org/jobs) exists.
Happy for input on the timing/frequency/content.

Jobs Board Reminder

---

uqcsbot/scripts/xkcd.py

As in title. This probably isn't the most efficient way to do this since the string slicing is hard-coded, but I doubt that would be a problem (unless xkcd decides to change what they've done for the last x number of years). Fixes #482

Ensure all things posted by uqcsbot are comics, fixes #482

---

test/test_advent.py
uqcsbot/scripts/advent.py

Also made formatting more consistent with other scripts.

Adding `-g` global points argument

---

setup.py

This fix works on my machine. Hopefully fixes prod problems from #565.

Add psycopg2 to setup.py requirements.
