scripts/id.js
The passthrough thing uses user IDs rather than names, if you want to use it to track yourself, you can get your own ID and identify yourself or anyone who offers you their id
=> Added a way to find out your own user id

scripts/exec.js
- This was needed to allow for both horizontal (ie: "!(caesar
h)!(caesar i)") and vertical (ie: "!(caesar !(caesar hi))")
=> Modified !exec's parsing from regex to token-based

scripts/reactify.js
Hi, I wrote a silly command `!reactify`. UQCSBot will react with appropriate emoji for the given word/words to the best of it's ability. Merging this will probably not break anything.
I've gone through the custom emoji of the UQCS slack and mapped each alphanumerical character to any relevant emoji I could find. It randomly selects from the possible emoji. Unfortunately does not work well with repeat characters unless you get lucky with the randomization and there's more than one possible emoji.
Demo is pretty bland since I don't have the custom emoji on my dummy slack so I just did numbers:
=> Added !reactify

scripts/button_listener.js, scripts/vote.js
Fancy voting buttons. ~~There's a couple obvious issues such as people voting multiple times, having no way to undo a vote and potentially annoying highlighting when someone votes. Decided to implement this separate from !voteythumbs for these reasons.~~
In order to run this another environmental variable is needed: `SLACK_VERIFICATION_TOKEN` which is just the verification token in the app (assuming the bot becomes an app). Also an interactive messages URL needs to be set. My setup just has this as <server>/vote right now but that's easy enough to change. 
Another thing to note is if uqcsbot is in app form this could probably be implemented as /vote and be cleaner.
Demo (Abstain removes existing vote):
=> Implemented !vote, button-based alternative!

scripts/pastexams.js
Given a course code, it will retrieve a list of all the available past exams and post their links to the channel. Works just like !ecp and !whatsdue in that if called within a subject channel, the course code can be omitted.
=> Added !pastexams

scripts/welcome.js
As per title, fixes two bugs from #166
1) display_name is optional, so instead we now default to `display_name` and resort to `name` as a back up (which is a required field)
2) Slack Web API default limits `conversations.members` to returning only 100 members. Added pagination code that utilises `next_cursor` to accurately yield _all_ members
=> Patched !welcome script (default name and API pagination)

scripts/welcome.js
When a user is welcomed to general, uqcsbot's welcome message will prevent wavie.js from :wave:ing at the user due to it becoming the new 'latest' message before the API request can be responded to.
To fix this, I have manually added a :wave: in welcome.js so that new #general users can be waved at :)
=> Added manual :wave: to welcome.js

scripts/stats.js
This PR does a few things
- Subscription system allowing people to subscribe to stats
- Stats reset and subscriptions published every Monday (might change this to fortnightly?)
- Arbitrary stats can be subscribed to and retrieved (aka `!stats !cat` will return the value associated with the `!cat` stat)
- Adds percentage statistic to room and command printouts
- Moved from API calls to RTM datastore for getting room names to remove the ability to DOS uqcsbot lol
- fixes #199 
- Removes tracking of direct messages to uqcsbot
=> added a subscriber system to !stats

scripts/stats.js
Subscription system will currently be broken as `_subscriber` was never added to the brain, and no code was in place to check otherwise.
This PR fixes that (and any future stats added to the system) by checking all default stats are present every time we get stats from the database.
Also fixes a mutation bug (`DEFAULT_STATS` was copied by reference and therefore being mutated-- not a big deal for now but probably not a good thing lol)
Note: this bug slipped through the gaps during testing because I had no database locally-- and this is only an issue to do with persistent storage
=> Ensure that any new default stats being added are added to the brain

uqcsbot/base.py
Runs all event handlers asynchronously. If a worker is written synchronously, runs it in a thread pool executor, else uses standard asyncio.
Using mobile data and github is being weird so this might be a bad merge.
Currently untested.
=> Add asyncio support

uqcsbot/base.py
This just allows the use of optional parameters in the bot.post_message function. For example:
```
attachments = [{
"fallback": "New ticket from Andrea Lee - Ticket #1943: Can't reset my password - https://groove.hq/path/to/ticket/1943",
"pretext": "New ticket from Andrea Lee",
"title": "Ticket #1943: Can't reset my password",
"title_link": "https://groove.hq/path/to/ticket/1943",
"text": "Help! I tried to reset my password but nothing happened!",
"color": "#7CD197"
}]
bot.post_message(command.channel, "", attachments=attachments)
```
Results in the following message:
=> Added ability to use optional parameters in post_message

uqcsbot/api.py, uqcsbot/base.py
Currently the channel list is only build using channels.list but this does not include the private messages the bot has with users. I just added the channels from the im.list. I also added a handler in the bot class which reloads all ims whenever a new team member joins (team_join event). This may cause an issue if the user immediately goes to the PM with the python bot and types a valid command. Not sure how to get around that.
Solution isn't particularly elegant and I am sure there is a lot to be improved.
=> Allows python bot to respond to commands in PMs

uqcsbot/scripts/wolfram.py
A single command !wolfram that does two things. Depending on the --full arg
!wolfram --full 2x+8
!wolfram 2x+8 --full
Examples:
!wolfram on the other hand returns just a short text response that can usually be replied to. For example:
If Wolfram cannot come up with a conversation for that question (seems to be a rare case) then a short answer is instead supplied using their short answers API. 
The app id you get from wolfram is free for less than 2000 requests a month which I doubt would ever be exceeded.
=> Added !wolfram command

README.md, uqcsbot/__init__.py, uqcsbot/base.py
Previously, users would have to set up their own remote developer environments in order to test slack-specific features. This required jumping through a lot of hoops such as creating their own workspace, adding custom bot integrations and messing with tokens and environment variables.
This PR brings back the communal Slack testing workspace we had for JSbot, with the added improvement of automagical bot allocation. Now, a user simply has to run with the `--dev` flag and a an available bot will be found and allocated to them for immediate use on the uqcstesting Slack.
This is obviously muuuUUUUUCH more beginner friendly by removing a large barrier of entry (complicated dev environment setups) for new developers looking to contribute to UQCSbot.
=> Introduced automatic bot allocation for easier and quicker dev testing

uqcsbot/api.py
Uses #276 as a base, but adds more sophisticated async logic.
We could totally cheat and just use the sync method in a call to `loop.run_in_executor` but this should theoretically play nicer with our event loop?
If we'd prefer less duplication over incredibly slight perf benefits, I'll rewrite.
=> Async Rate Limiting

uqcsbot/api.py, uqcsbot/base.py, uqcsbot/scripts/acronym.py, uqcsbot/scripts/caesar.py, uqcsbot/scripts/cat.py, uqcsbot/scripts/cookbook.py, uqcsbot/scripts/dog.py, uqcsbot/scripts/echo.py, uqcsbot/scripts/ecp.py, uqcsbot/scripts/events.py, uqcsbot/scripts/help.py, uqcsbot/scripts/pastexams.py, uqcsbot/scripts/radar.py, uqcsbot/scripts/repo.py, uqcsbot/scripts/spider.py, uqcsbot/scripts/voteythumbs.py, uqcsbot/scripts/wakie.py, uqcsbot/scripts/wavie.py, uqcsbot/scripts/welcome.py, uqcsbot/scripts/wiki.py, uqcsbot/scripts/wolfram.py
Brings back the !help functionality from jsbot. This command allows users to discover the helper docstrings for all uqcsbot's commands-- and additionally allows specified querying for a certain command's docstring.
Functional demonstration:
In addition, this PR added the ability for commands to know which user called them. It also changed how direct channels were stored by setting the previously redundant name to be the direct message user's id. This allows for much easier reverse lookup of calling user's direct message channel.
As always, feedback and reviews are much appreciated :^)
Fixes #245.
=> Added !help command

uqcsbot/scripts/events.py
I found two bugs:
1) `.dt` can return `date` objects, which will error later on when we tried to compare them to `datetime` objects
2) `filter_events` did not have a return path for when `full` was given, so it was setting `events = None`
I fixed these by adding datetime conversion as well as adding in a default return path for cases such as `full`.
Fixes #289.
=> Fixed !events

test/conftest.py, uqcsbot/api.py, uqcsbot/base.py, uqcsbot/scripts/acronym.py, uqcsbot/scripts/define.py, uqcsbot/scripts/ecp.py, uqcsbot/scripts/events.py, uqcsbot/scripts/help.py, uqcsbot/scripts/mock.py, uqcsbot/scripts/pastexams.py, uqcsbot/scripts/voteythumbs.py, uqcsbot/scripts/wakie.py, uqcsbot/scripts/welcome.py, uqcsbot/scripts/wiki.py, uqcsbot/scripts/wolfram.py, uqcsbot/util/status_reacts.py
Swap all the core stuff for a single function `bot.get_event_loop()`, which allows you to use asyncio within the scope of a single command by getting an event loop.
All commands are run in threads using a `concurrent.futures.ThreadPoolExecutor`.
Coroutines as commands no longer works.
Fixes #282. Fixes #292.
=> Removed async as a core part of the framework

uqcsbot/util/uq_course_util.py
This PR makes it so that if we can't parse a due date, we assume that it has not passed yet and return it to the user. This is better than the alternative of just not showing it at all.
Ideally, we want to be able to parse all potential due dates. As such, I've added a TODO for this; but this PR fix should suffice for now.
=> Added exception handling for unparsable dates

uqcsbot/base.py
The slack client library we're using provides auto-reconnect logic for us that we weren't using. This PR adds that logic through setting the `auto_reconnect` flag and also sets the `with_team_state` flag to `False` for a lighter connection (which is recommended for larger teams such as ours)
See: https://slackapi.github.io/python-slackclient/real_time_messaging.html#rtm-start-vs-rtm-connect
=> Added auto reconnect and no team state flags

uqcsbot/scripts/attic.py
replace access by key to `.get()`
=> Don't crash UQCSBot on missing Google API key

uqcsbot/scripts/latex.py
This is a bit more general than the title implies, but it fixes the constant errors in logs whenever someone updates a message.
=> !latex: Remove errors on message types without `text` attr

test/test_umart.py, test/umart_products_list_search.html, uqcsbot/scripts/umart.py
Turns out that when you download HTML it expands it to the full link and not just the identifier as seen when inspecting elements in the browser. For whatever reason, I didn't catch this and changed the formatting thinking I had borked it earlier. 
This PR fixes that mistake.
=> Fix for umart

uqcsbot/scripts/yt.py
We were getting these errors whenever !yt was used:
```
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
File "/srv/uqcsbot/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/srv/uqcsbot/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'
During handling of the above exception, another …
```
=> Patched !yt

uqcsbot/scripts/urban.py
it seems they updated their api and removed the `result_type` field, so I've removed that and instead just check the length of the returned definitions list.
=> Patched !urban

uqcsbot/scripts/welcome.py
As per title. This move was made such that the member count accurately reflects the number provided by slack-- which seems to ignore bots.
I also moved the time consuming welcome messages to after the milestone calculation as there is a large gap between the "Welcome, {USER}!" and ":tada: XXXX members! :tada:" otherwise.
=> Remove bots from welcome count

test/conftest.py, test/test_welcome.py, uqcsbot/api.py, uqcsbot/scripts/welcome.py
we were getting `ValueError: list.remove(x): x not in list` errors upon members leaving channels, so I added a check before adding/removing a member. This required updating the test suite, which previously was only adding one member type 50 times. I added the ability to properly add test users and channels while fixing those tests.
=> Patched member leaving channel bug

uqcsbot/scripts/jobs.py
As per title. Fixes #344. Feedback welcome.
- Messages user with #jobs-bulletin rules when they join.
- Reminds users who post in #jobs-bulletin of the rules.
- Messages #jobs-bulletin directing conversation to DM or #jobs-discussion.
=> added jobs-bulletin watchdog

uqcsbot/utils/uq_course_utils.py
Computes the hex offering string to use in get_course_profile_url so the current semester is highlighted and parsed.
In June and earlier, gets semester 1, otherwise gets semester 2. This is the same as get_current_exam_period so it should be fine..? I couldn't really test this because #369 only occurred when both semesters 1 and 2 were listed under "Current course offerings" during the first couple weeks of sem 2.
Also, it would be nice to have an argument in !whatsdue for which semester and campus to query.
=> Fixed !whatsdue for semester 2 (fixes #369)

uqcsbot/scripts/radar.py
A problem with the radar command is that it is fetched for each request, so it shows the radar at the time when it was loaded by the user, not when it was posted to slack. I've updated the service to take a timestamp and it'll use a cached image from that timestamp if available.
=> Update !radar with new caching

uqcsbot/scripts/xkcd.py
This is based on the current release timetable of 4AM UTC, Mon, Wed, Fri, but when we give the bot back its brain we can move this to checking the RSS feed to more safely avoid duplicates.
=> Post new xkcd comics on release

uqcsbot/scripts/trivia.py
This adds an -n flag to the command which asks n questions in succession.
There is currently a question cap of 30 and the command is limited to the trivia and bot-testing channels to avoid spam. Let me know if you want this changed etc. 
There is no way to stop the sequence once it starts as that would require storing the job as far as I know? Can add this later along with the leaderboard (see below).
This also adds a daily job to the trivia channel which asks a new question at 12. I also have a branch that contains the code for a persistent leaderboard that tracks everyone's scores on the daily trivia. 
I have not included it here while I wait for a proper interface on the bot for using the database and not a hacky solution. This is why there may be some extra code in there that isn't …
=> Add an -n to trivia and a daily trivia in #trivia

uqcsbot/scripts/welcome.py
This will increase engagement, as most people, after joining, never log back on, mainly because they used the web client. 
I'm open to better copy, suggest better versions and those with the most likes, I'll amend the commit.
=> Add hint to download Slack app

setup.py
Fixes the recent outage issue - a single read wasn't happening instantly so it was just reacting as if the socket was closed.
=> Add a constraint on `websocket-client`

uqcsbot/scripts/radar.py
Tested with a bot in uqcstesting. With this patch, we have pretty previews again.
I tried using the new [blocks API](https://api.slack.com/reference/messaging/blocks#image) instead of the old [attachments API](https://api.slack.com/docs/outmoded-messaging) but it seems to have a special grudge against bom.lambda.tools - worked fine with a similar URL from my ngrok.
=> Expand radar image again to fix #387

uqcsbot/scripts/jobs.py
The slack api requests you just send <@user_id> instead of <@user_id|@user_name>. Now we're doing that
=> Fix jobs posting bug

uqcsbot/scripts/trivia.py
The reactions for trivia questions should now always appear in the correct order instead of changing order due to timestamp issues.
=> Fixes the order of trivia reactions

test/test_crates.py, uqcsbot/scripts/crates.py
Adds a command !crates which does a whole bunch of stuff related to crates.io.
To summarise, it can search crates by exact name or it can return a list of crates narrowed down by a search term, category and author. It can also return a list of all category names and give more in depth detail about a category. Finally, it can return publicly available information about a user. Examples of all of these scenarios below.
=> Adds a !crates command

test/test_crisis.py, uqcsbot/scripts/crisis.py
Re-merge of #435 after Nick did some stuff with the tests. Content is identical.
All are aliases for the same thing - provide a list of crisis resources for
quick reference.
=> Create !crisis, !mentalhealth and !emergency commands

uqcsbot/scripts/hoogle.py
Fixes #433
For reference, the response format directly returns a list of dicts now. Example dict:
```
{"url":"https://hackage.haskell.org/package/base/docs/Prelude.html#v:const","module":{"url":"https://hackage.haskell.org/package/base/docs/Prelude.html","name":"Prelude"},"package":{"url":"https://hackage.haskell.org/package/base","name":"base"},"item":"<span class=name><s0>const</s0></span> :: a -&gt; b -&gt; a","type":"","docs":"<tt>const x</tt> is a unary function which evaluates to <tt>x</tt> for\nall inputs.\n\n<pre>\n&gt;&gt;&gt; const 42 \"hello\"\n42\n</pre>\n\n<pre>\n&gt;&gt;&gt; map (const 42) [0..3]\n[42,42,42,42]\n</pre>\n"}
```
The responses now also contain HTML markup. It's trivial to strip from the type sig but less so from the docs segment without the formatting for the …
=> Naive fix for hoogle. Strip html and formatting

test/parking.html, test/test_parking.py, uqcsbot/scripts/parking.py
UQ Properties and Facilities seem to like randomly changing the amount of whitespace on their parking availability webpage (see changes to `tests/parking.html`). This pull should allow `!parking` to work no matter how much whitespace they wish to add/remove.
=> Increase `!parking` robustness

uqcsbot/utils/uq_course_utils.py
The whatsdue script was broken due to a change in url format. Closes #453
=> Fixes determining course code to fit new url format

uqcsbot/utils/uq_course_utils.py
Fixes !whatsdue and !ecp. They broke because you now need to supply a user agent when making a request to the site.
I also added some more error handling to stop it from hanging as often.
Closes #473 and closes #472
=> Whatsdue fix 050519

test/test_yelling.py, uqcsbot/scripts/yelling.py
Failure to yell in threads now causes UQCS to respond in the thread (and to #yelling if reply was also to #yelling).
Now correctly fails to consider `&`, `<` and `>` as not yelling.
=> Fix yelling.py for threads and punctuation

uqcsbot/utils/command_utils.py
As in title. This probably isn't the most efficient way to do this but there is little to no perceptible slowdown. Addresses #481
=> Fix duplicated !help messages for aliased commands, fixes #481

uqcsbot/scripts/latex.py
Changed background of latex images from transparent to white so that they can be viewed on dark mode
=> Add background to latex images

test/test_yelling.py, uqcsbot/scripts/yelling.py
Some #yelling replies post lower case text, this allows only those replies.
Also allows underscored emojis without complaining
=> Fix tests in #yelling

setup.py, test/conftest.py, test/test_ascii.py, tox.ini, uqcsbot/__init__.py, uqcsbot/api.py, uqcsbot/base.py, uqcsbot/scripts/yelling.py
This updates our slack client and testing code to the latest version. I've also taken the liberty of prepping uqcsbot for the "two different token" aka "granular scopes" update that destroyed it last time.
Right now we're having to use an old-style token spun up specifically but if they ever reenable bot users we'll probably have to do something different there. If they never do, we should rewrite to use the events API.
=> Slackclient v2 full update

setup.py, test/conftest.py, test/test_ascii.py, tox.ini, uqcsbot/__init__.py, uqcsbot/api.py, uqcsbot/base.py, uqcsbot/scripts/cat.py, uqcsbot/scripts/mock.py, uqcsbot/scripts/yelling.py
This is a cleaned up version of my PR #503, which also includes some extra stuff like a partial fix for #493 (to be implemented separately per script). There's a lot going on soz. This is needed for medium term UQCSBot stability.
=> UQCSBot: Ressurection

uqcsbot/api.py, uqcsbot/scripts/welcome.py
Not sure why the KeyError problem occurs. Welcome seems to be firing correctly in the live version but did not work on testing without this change.
Apart from that, updated committee users after 2020 SGM (add Alby, James D., Paul; remove Jack, Raghav, Brian).
Also spaced out messages to show where the pauses will be between message parts.
KeyError exception below:
```
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/__main__.py", line 2, in <module>
main()
File "/srv/uqcsbot/lib/python3.6/site-packages/uqcsbot/__init__.py", line 160, in main
bot.run(user_token, bot_token)
File …
```
=> Fix KeyError on missing users and update committee after 2020 SGM.

test/test_channel_log.py, test/test_emoji_log.py, uqcsbot/scripts/channel_log.py
Whenever a channel is created, announces in `#uqcs-meta`.
(Public channels only.)
=> Create Channel Log

test/test_yelling.py, uqcsbot/scripts/yelling.py
Fixes #495 by using the "human" user id.
=> Fix occational `test_yelling` failures

test/test_help.py, uqcsbot/scripts/help.py
`!help` (with no arguments) still responds via direct message.
=> `!help command` to respond in same channel

uqcsbot/api.py
Addresses #490  
Apparently the fields of a deleted channel get switched around such that the channel field now returns the channel id.
=> Anti Deleted Channel Bot Killing

test/test_events.py, uqcsbot/scripts/events.py
Closes #120 
Should handle recurring events which are later cancelled (e.g. CPG this week). The number of recurring events in the full calendar is limited to 3 to reduce the clutter.
=> Recurring events
